import type { NeighborhoodUser, NeighborhoodItem, NeighborhoodWant, Offer } from './types'

export const seedUsers: NeighborhoodUser[] = [
  { id: 'u1', name: 'User A', locationKey: 'campus', locationValue: 'North Campus' },
  { id: 'u2', name: 'User B', locationKey: 'campus', locationValue: 'North Campus' },
  { id: 'u3', name: 'User C', locationKey: 'neighborhood', locationValue: 'Mission District' },
  { id: 'u4', name: 'User D', locationKey: 'neighborhood', locationValue: 'Mission District' },
  { id: 'u5', name: 'User E', locationKey: 'zip', locationValue: '94110' },
  { id: 'u6', name: 'User F', locationKey: 'zip', locationValue: '94110' },
  { id: 'u7', name: 'User G', locationKey: 'campus', locationValue: 'South Campus' },
  { id: 'u8', name: 'User H', locationKey: 'campus', locationValue: 'North Campus' },
  { id: 'u9', name: 'User I', locationKey: 'neighborhood', locationValue: 'SOMA' },
  { id: 'u10', name: 'User J', locationKey: 'neighborhood', locationValue: 'Mission District' },
  { id: 'u11', name: 'User K', locationKey: 'zip', locationValue: '94103' },
  { id: 'u12', name: 'User L', locationKey: 'zip', locationValue: '94110' },
  { id: 'u13', name: 'User M', locationKey: 'campus', locationValue: 'North Campus' },
  { id: 'u14', name: 'User N', locationKey: 'neighborhood', locationValue: 'Castro' },
  { id: 'u15', name: 'User O', locationKey: 'zip', locationValue: '94114' },
  { id: 'u16', name: 'User P', locationKey: 'campus', locationValue: 'South Campus' },
  { id: 'u17', name: 'User Q', locationKey: 'neighborhood', locationValue: 'Mission District' },
  { id: 'u18', name: 'User R', locationKey: 'zip', locationValue: '94110' },
  { id: 'u19', name: 'User S', locationKey: 'campus', locationValue: 'North Campus' },
  { id: 'u20', name: 'User T', locationKey: 'neighborhood', locationValue: 'SOMA' },
  { id: 'u21', name: 'User U', locationKey: 'campus', locationValue: 'North Campus' },
  { id: 'u22', name: 'User V', locationKey: 'zip', locationValue: '94110' },
  { id: 'u23', name: 'User W', locationKey: 'neighborhood', locationValue: 'Mission District' },
  { id: 'u24', name: 'User X', locationKey: 'campus', locationValue: 'South Campus' },
  { id: 'u25', name: 'User Y', locationKey: 'neighborhood', locationValue: 'SOMA' },
]

export const seedItems: NeighborhoodItem[] = [
  {
    id: 'ni1',
    userId: 'u1',
    name: 'iPhone 12',
    category: 'Electronics',
    condition: 'Good',
    wouldLetGoFor: 300,
    estimatedValue: 350,
    likelihoodToSell: 'if good offer',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'ni2',
    userId: 'u2',
    name: 'IKEA Desk',
    category: 'Furniture',
    condition: 'Good',
    wouldLetGoFor: 50,
    estimatedValue: 80,
    likelihoodToSell: 'want gone',
    shippingPreference: 'local only',
  },
  {
    id: 'ni3',
    userId: 'u3',
    name: 'Road Bike',
    category: 'Sports',
    condition: 'Like New',
    wouldLetGoFor: 200,
    estimatedValue: 250,
    likelihoodToSell: 'if good offer',
    shippingPreference: 'local only',
  },
  {
    id: 'ni4',
    userId: 'u4',
    name: 'Winter Coat',
    category: 'Clothing',
    condition: 'Good',
    wouldLetGoFor: 40,
    estimatedValue: 60,
    likelihoodToSell: 'maybe',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'ni5',
    userId: 'u5',
    name: 'Espresso Machine',
    category: 'Kitchen',
    condition: 'Like New',
    wouldLetGoFor: 150,
    estimatedValue: 200,
    likelihoodToSell: 'if good offer',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'ni6',
    userId: 'u6',
    name: 'Calculus Textbook',
    category: 'Books',
    condition: 'Good',
    wouldLetGoFor: 30,
    estimatedValue: 50,
    likelihoodToSell: 'want gone',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'ni7',
    userId: 'u7',
    name: 'PlayStation 5',
    category: 'Electronics',
    condition: 'Like New',
    wouldLetGoFor: 400,
    estimatedValue: 450,
    likelihoodToSell: 'maybe',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'ni8',
    userId: 'u8',
    name: 'Dining Table',
    category: 'Furniture',
    condition: 'Good',
    wouldLetGoFor: 120,
    estimatedValue: 180,
    likelihoodToSell: 'if good offer',
    shippingPreference: 'local only',
  },
  {
    id: 'ni9',
    userId: 'u9',
    name: 'Yoga Mat',
    category: 'Sports',
    condition: 'Like New',
    wouldLetGoFor: 15,
    estimatedValue: 25,
    likelihoodToSell: 'want gone',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'ni10',
    userId: 'u10',
    name: 'Leather Jacket',
    category: 'Clothing',
    condition: 'Good',
    wouldLetGoFor: 80,
    estimatedValue: 120,
    likelihoodToSell: 'if good offer',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'ni11',
    userId: 'u11',
    name: 'Air Fryer',
    category: 'Kitchen',
    condition: 'New',
    wouldLetGoFor: 50,
    estimatedValue: 70,
    likelihoodToSell: 'want gone',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'ni12',
    userId: 'u12',
    name: 'Harry Potter Set',
    category: 'Books',
    condition: 'Good',
    wouldLetGoFor: 40,
    estimatedValue: 60,
    likelihoodToSell: 'maybe',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'ni13',
    userId: 'u13',
    name: 'MacBook Pro 2019',
    category: 'Electronics',
    condition: 'Good',
    wouldLetGoFor: 600,
    estimatedValue: 700,
    likelihoodToSell: 'if good offer',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'ni14',
    userId: 'u14',
    name: 'Office Chair',
    category: 'Furniture',
    condition: 'Like New',
    wouldLetGoFor: 100,
    estimatedValue: 150,
    likelihoodToSell: 'if good offer',
    shippingPreference: 'local only',
  },
  {
    id: 'ni15',
    userId: 'u15',
    name: 'Tennis Racket',
    category: 'Sports',
    condition: 'Good',
    wouldLetGoFor: 60,
    estimatedValue: 90,
    likelihoodToSell: 'maybe',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'ni16',
    userId: 'u16',
    name: 'Sneakers',
    category: 'Clothing',
    condition: 'Like New',
    wouldLetGoFor: 50,
    estimatedValue: 80,
    likelihoodToSell: 'want gone',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'ni17',
    userId: 'u17',
    name: 'Blender',
    category: 'Kitchen',
    condition: 'Good',
    wouldLetGoFor: 30,
    estimatedValue: 50,
    likelihoodToSell: 'if good offer',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'ni18',
    userId: 'u18',
    name: 'Economics Textbook',
    category: 'Books',
    condition: 'Good',
    wouldLetGoFor: 35,
    estimatedValue: 55,
    likelihoodToSell: 'want gone',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'ni19',
    userId: 'u19',
    name: 'iPad Air',
    category: 'Electronics',
    condition: 'Like New',
    wouldLetGoFor: 350,
    estimatedValue: 400,
    likelihoodToSell: 'if good offer',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'ni20',
    userId: 'u20',
    name: 'Bookshelf',
    category: 'Furniture',
    condition: 'Good',
    wouldLetGoFor: 40,
    estimatedValue: 70,
    likelihoodToSell: 'want gone',
    shippingPreference: 'local only',
  },
  {
    id: 'ni21',
    userId: 'u2',
    name: 'Vintage Vinyl Records',
    category: 'Collectibles',
    condition: 'Good',
    estimatedValue: 500,
    likelihoodToSell: 'maybe',
    shippingPreference: 'shipping ok',
    isSpecialCollectible: true,
  },
  {
    id: 'ni22',
    userId: 'u5',
    name: 'Signed Baseball Card',
    category: 'Collectibles',
    condition: 'Like New',
    estimatedValue: 800,
    likelihoodToSell: 'maybe',
    shippingPreference: 'shipping ok',
    isSpecialCollectible: true,
  },
  {
    id: 'ni23',
    userId: 'u21',
    name: 'AirPods Pro',
    category: 'Electronics',
    condition: 'Good',
    wouldLetGoFor: 120,
    estimatedValue: 150,
    likelihoodToSell: 'if good offer',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'ni24',
    userId: 'u22',
    name: 'Standing Lamp',
    category: 'Furniture',
    condition: 'Good',
    wouldLetGoFor: 25,
    estimatedValue: 40,
    likelihoodToSell: 'want gone',
    shippingPreference: 'local only',
  },
  {
    id: 'ni25',
    userId: 'u23',
    name: 'Skateboard',
    category: 'Sports',
    condition: 'Good',
    wouldLetGoFor: 50,
    estimatedValue: 75,
    likelihoodToSell: 'if good offer',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'ni26',
    userId: 'u24',
    name: 'Hoodie',
    category: 'Clothing',
    condition: 'Like New',
    wouldLetGoFor: 30,
    estimatedValue: 50,
    likelihoodToSell: 'want gone',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'ni27',
    userId: 'u25',
    name: 'Rice Cooker',
    category: 'Kitchen',
    condition: 'Good',
    wouldLetGoFor: 40,
    estimatedValue: 60,
    likelihoodToSell: 'if good offer',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'ni28',
    userId: 'u1',
    name: 'Programming Book Bundle',
    category: 'Books',
    condition: 'Good',
    wouldLetGoFor: 60,
    estimatedValue: 90,
    likelihoodToSell: 'want gone',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'ni29',
    userId: 'u3',
    name: 'Nintendo Switch',
    category: 'Electronics',
    condition: 'Good',
    wouldLetGoFor: 200,
    estimatedValue: 250,
    likelihoodToSell: 'if good offer',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'ni30',
    userId: 'u4',
    name: 'Side Table',
    category: 'Furniture',
    condition: 'Good',
    wouldLetGoFor: 30,
    estimatedValue: 50,
    likelihoodToSell: 'want gone',
    shippingPreference: 'local only',
  },
]

export const seedWants: NeighborhoodWant[] = [
  {
    id: 'nw1',
    userId: 'u2',
    name: 'iPhone',
    maxOffer: 350,
    urgency: 'interested',
    category: 'Electronics',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'nw2',
    userId: 'u3',
    name: 'Desk',
    maxOffer: 60,
    urgency: 'casual',
    category: 'Furniture',
    shippingPreference: 'local only',
  },
  {
    id: 'nw3',
    userId: 'u4',
    name: 'Bike',
    maxOffer: 250,
    urgency: 'urgent',
    category: 'Sports',
    shippingPreference: 'local only',
  },
  {
    id: 'nw4',
    userId: 'u5',
    name: 'Winter Jacket',
    maxOffer: 50,
    urgency: 'casual',
    category: 'Clothing',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'nw5',
    userId: 'u6',
    name: 'Coffee Machine',
    maxOffer: 180,
    urgency: 'interested',
    category: 'Kitchen',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'nw6',
    userId: 'u7',
    name: 'Textbooks',
    maxOffer: 40,
    urgency: 'urgent',
    category: 'Books',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'nw7',
    userId: 'u8',
    name: 'Gaming Console',
    maxOffer: 450,
    urgency: 'interested',
    category: 'Electronics',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'nw8',
    userId: 'u9',
    name: 'Table',
    maxOffer: 150,
    urgency: 'casual',
    category: 'Furniture',
    shippingPreference: 'local only',
  },
  {
    id: 'nw9',
    userId: 'u10',
    name: 'Yoga Equipment',
    maxOffer: 30,
    urgency: 'casual',
    category: 'Sports',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'nw10',
    userId: 'u11',
    name: 'Jacket',
    maxOffer: 100,
    urgency: 'interested',
    category: 'Clothing',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'nw11',
    userId: 'u12',
    name: 'Kitchen Appliance',
    maxOffer: 60,
    urgency: 'casual',
    category: 'Kitchen',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'nw12',
    userId: 'u13',
    name: 'Books',
    maxOffer: 50,
    urgency: 'casual',
    category: 'Books',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'nw13',
    userId: 'u14',
    name: 'Laptop',
    maxOffer: 650,
    urgency: 'urgent',
    category: 'Electronics',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'nw14',
    userId: 'u15',
    name: 'Chair',
    maxOffer: 120,
    urgency: 'interested',
    category: 'Furniture',
    shippingPreference: 'local only',
  },
  {
    id: 'nw15',
    userId: 'u16',
    name: 'Sports Equipment',
    maxOffer: 70,
    urgency: 'casual',
    category: 'Sports',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'nw16',
    userId: 'u17',
    name: 'Shoes',
    maxOffer: 60,
    urgency: 'interested',
    category: 'Clothing',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'nw17',
    userId: 'u18',
    name: 'Blender',
    maxOffer: 40,
    urgency: 'casual',
    category: 'Kitchen',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'nw18',
    userId: 'u19',
    name: 'Textbook',
    maxOffer: 40,
    urgency: 'urgent',
    category: 'Books',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'nw19',
    userId: 'u20',
    name: 'Tablet',
    maxOffer: 380,
    urgency: 'interested',
    category: 'Electronics',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'nw20',
    userId: 'u1',
    name: 'Shelf',
    maxOffer: 50,
    urgency: 'casual',
    category: 'Furniture',
    shippingPreference: 'local only',
  },
  {
    id: 'nw21',
    userId: 'u21',
    name: 'Headphones',
    maxOffer: 140,
    urgency: 'interested',
    category: 'Electronics',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'nw22',
    userId: 'u22',
    name: 'Lamp',
    maxOffer: 30,
    urgency: 'casual',
    category: 'Furniture',
    shippingPreference: 'local only',
  },
  {
    id: 'nw23',
    userId: 'u23',
    name: 'Board',
    maxOffer: 60,
    urgency: 'interested',
    category: 'Sports',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'nw24',
    userId: 'u24',
    name: 'Sweater',
    maxOffer: 35,
    urgency: 'casual',
    category: 'Clothing',
    shippingPreference: 'shipping ok',
  },
  {
    id: 'nw25',
    userId: 'u25',
    name: 'Cooker',
    maxOffer: 50,
    urgency: 'interested',
    category: 'Kitchen',
    shippingPreference: 'shipping ok',
  },
]

export const seedOffers: Offer[] = [
  {
    id: 'no1',
    wantId: 'nw1',
    itemId: 'ni1',
    buyerId: 'u2',
    sellerId: 'u1',
    amount: 320,
    status: 'pending',
    createdAt: Date.now() - 3600000,
  },
  {
    id: 'no2',
    wantId: 'nw5',
    itemId: 'ni5',
    buyerId: 'u6',
    sellerId: 'u5',
    amount: 160,
    status: 'pending',
    createdAt: Date.now() - 7200000,
  },
  {
    id: 'no3',
    wantId: 'nw7',
    itemId: 'ni7',
    buyerId: 'u8',
    sellerId: 'u7',
    amount: 420,
    status: 'pending',
    createdAt: Date.now() - 1800000,
  },
  {
    id: 'no4',
    wantId: 'nw13',
    itemId: 'ni13',
    buyerId: 'u14',
    sellerId: 'u13',
    amount: 620,
    status: 'pending',
    createdAt: Date.now() - 5400000,
  },
]
